# Generated by Django 4.2.5 on 2023-09-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_customuser_email_alter_customuser_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telefone',
            new_name='phone',
        ),
    ]
